# ============================================================
# Dev Environment — Kustomize Overlay
# - In-cluster Redis (no ElastiCache)
# - Minimal resource limits
# - Image tags auto-updated by CI pipeline
# ============================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base
- namespace.yaml

# ─── Image tags (auto-updated by CI pipeline) ────────────
# CI runs: kustomize edit set image <svc>=<ecr_url>:<tag>
images:
- name: adservice
  newName: 798836978890.dkr.ecr.ap-southeast-1.amazonaws.com/online-boutique/adservice
  newTag: sha-18d3e3478875c7a9dd642fc613d7a2b393df8e03
- name: cartservice
  newName: 798836978890.dkr.ecr.ap-southeast-1.amazonaws.com/online-boutique/cartservice
  newTag: sha-18d3e3478875c7a9dd642fc613d7a2b393df8e03
- name: checkoutservice
  newName: 798836978890.dkr.ecr.ap-southeast-1.amazonaws.com/online-boutique/checkoutservice
  newTag: sha-18d3e3478875c7a9dd642fc613d7a2b393df8e03
- name: currencyservice
  newName: 798836978890.dkr.ecr.ap-southeast-1.amazonaws.com/online-boutique/currencyservice
  newTag: sha-18d3e3478875c7a9dd642fc613d7a2b393df8e03
- name: emailservice
  newName: 798836978890.dkr.ecr.ap-southeast-1.amazonaws.com/online-boutique/emailservice
  newTag: sha-18d3e3478875c7a9dd642fc613d7a2b393df8e03
- name: frontend
  newName: 798836978890.dkr.ecr.ap-southeast-1.amazonaws.com/online-boutique/frontend
  newTag: sha-18d3e3478875c7a9dd642fc613d7a2b393df8e03
- name: loadgenerator
  newName: 798836978890.dkr.ecr.ap-southeast-1.amazonaws.com/online-boutique/loadgenerator
  newTag: sha-18d3e3478875c7a9dd642fc613d7a2b393df8e03
- name: paymentservice
  newName: 798836978890.dkr.ecr.ap-southeast-1.amazonaws.com/online-boutique/paymentservice
  newTag: sha-18d3e3478875c7a9dd642fc613d7a2b393df8e03
- name: productcatalogservice
  newName: 798836978890.dkr.ecr.ap-southeast-1.amazonaws.com/online-boutique/productcatalogservice
  newTag: sha-18d3e3478875c7a9dd642fc613d7a2b393df8e03
- name: recommendationservice
  newName: 798836978890.dkr.ecr.ap-southeast-1.amazonaws.com/online-boutique/recommendationservice
  newTag: sha-18d3e3478875c7a9dd642fc613d7a2b393df8e03
- name: shippingservice
  newName: 798836978890.dkr.ecr.ap-southeast-1.amazonaws.com/online-boutique/shippingservice
  newTag: sha-18d3e3478875c7a9dd642fc613d7a2b393df8e03

commonLabels:
  environment: dev
